### ISSUE TITLE
Permettre une modification du rythme de défilement

### ISSUE THREAD

**Issue by ipante** [ibornes/Votations#4]
Vous pouvez vous inspirer de notre projet : https://github.com/maladesimaginaires/intnetviz

**Comment by ibornes** [comment]
Défilement prop. au nombre de votations.
On peut modifier le défilement en choisissant une période plus courte.
Rajout (dans le select) des années 1970, 1995, 2005, 2015 pour proposer des périodes contenant environ le même nombre de votations.
Idéal de prendre les années qui se suivent (par exemple, 1970-1980, 2000-2005, etc.)
