### ISSUE TITLE
Suggestion : ajouter un "select" pour la liste des objets

### ISSUE THREAD

**Issue by ipante** [ibornes/Votations#5]
Lequel permettrait d'aller directement à l'objet d'intérêt. Ici encore, vous pouvez vous inspirer de notre projet : https://github.com/maladesimaginaires/intnetviz

**Comment by ibornes** [comment]
Ajour d'un select pour les votations (591 votations).

**Comment by ipante** [comment]
Parfait. Je vous propose d'utiliser un événement 'onselect' pour vous dispenser du second bouton "lancer". Vous pourrez ensuite fermer cette issue, ainsi que toutes les autres!

**Comment by ibornes** [comment]
Bonne idée.
Ajouté "onchange* sur le select.
