### ISSUE TITLE
Evolution bidirectionnelle

### ISSUE THREAD

**Issue by ipante** [ibornes/Votations#7]
Il est actuellement possible de sélectionner un intervalle qui "remonte le temps" (2010 à 2007). Est-ce voulu? Peut-être qu'il serait intéressant de le corriger si tel n'est pas le cas. Mais c'est un élément mineur.

**Comment by ibornes** [comment]
C'est voulu. En histoire, il est intéressant de pouvoir analyser les évolutions dans les deux directions.
