### ISSUE TITLE
Déplacement du nom de l'initiative

### ISSUE THREAD

**Issue by ipante** [ibornes/Votations#9]
Il arrive que le nom de l'initiative soit trop long et qu'il dépasse à gauche de la page. Peut-être devriez-vous l'aligner à gauche et le laisser déborder à droite. Dans tous les cas, dans son placement actuel, le titre de l'initiative n'est pas immédiatement repéré. Au vu de l'importance de l'information, il serait intéressant de la mettre davantage en valeur (notamment par un placement gauche).

**Comment by ibornes** [comment]
Justification à gauche du libellé de la votation effectuée
